### ISSUE TITLE
Warning: solve(): system is singular

### ISSUE THREAD

**Issue by Agenetics** [uqrmaie1/admixtools#27]
Hello, 

There are various instances while running the qpadm() function on Admixtools2 wherein the R console shows me warnings like these, but continues processing and delivers the output as required.

`warning: solve(): system is singular (rcond: 2.94665e-17); attempting approx solution`

`warning: solve(): system is singular (rcond: 3.35258e-17); attempting approx solution`

`warning: solve(): system is singular (rcond: 3.31962e-17); attempting approx solution`

Many times, I do not get such warnings.

What is the reason for this, and how does this impact the validity of the output?

Thank you.

**Comment by uqrmaie1** [comment]
It's been a while since I've seen this warning. Generally it suggests that there is some numerical instability, which could be for a few reasons, for example because there is very little differential drift separating two or more populations. It's possible that this results in very large standard errors for the weights, but I don't think it necessarily has to be a problem.

**Comment by Agenetics** [comment]
Thank you.
