### ISSUE TITLE
only estimated f2 in qpGraph result

### ISSUE THREAD

**Issue by leovallini** [uqrmaie1/admixtools#5]
Dear author,

I noticed that I do not obtain the fitted f2 values(as well as no diff and Z) in the results when running qpGraph() but only the estimated one and the standard error. On the other hand I get both fitted, estimated, se and Z in the f3 and f4; but in the early phases of "graph exploration" it is not easy to use just those to understand what needs to be corrected.
Am I missing some optional parameters to return the fitted f2 values or did you forget to implement it (the help of the function says I should get both)?

Thanks for your help,

Leonardo

**Comment by uqrmaie1** [comment]
The fitted f2 values are not part of the output for the same reason that f4 is not returned by default: it would make the `qpgraph` function slower. Since f2 is a special case of f4 with only two different populations, you can get the f2 SE and Z-scores like this:
`qpgraph(f2_blocks, graph, return_f4 = TRUE)$f4 %>% filter(pop1 == pop3, pop2 == pop4)`.
Thanks for pointing this out, I will mention it in the documentation!

**Comment by leovallini** [comment]
Thanks a lot for the quick answer, it was easier than I thought.
I am closing this issue.

Leonardo

**Comment by uqrmaie1** [comment]
To make this a bit more consistent, I have changed the `return_f4` argument to `return_fstats` in the latest commit. Setting this to `TRUE` will return fitted and estimated f2 and f4. By default, only fitted and estimated f3 will be returned.
